spring:

  datasource:
    url: ${DB_URL}
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}
    driver-class-name: org.postgresql.Driver

  jpa:
    open-in-view: false
    hibernate:
      ddl-auto: update
    show-sql: false
    properties:
      hibernate:
        format_sql: false

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: ${GOOGLE_CLIENT_ID:dummy}
            client-secret: ${GOOGLE_CLIENT_SECRET:dummy}

jwt:
  secret: ${JWT_SECRET}
  expiration: 86400000

marketdata:
  api:
    key: ${MARKETDATA_API_KEY}
  base:
    url: https://www.alphavantage.co

springdoc:
  api-docs:
    enabled: false

  swagger-ui:
    enabled: false

app:
  frontend:
    allowed-origins: ${FRONTEND_ALLOWED_ORIGINS}

management:
  endpoints:
    web:
      exposure:
        include: health

  endpoint:
    health:
      show-details: never

server:
  forward-headers-strategy: framework