spring:

  datasource:
    url: jdbc:postgresql://localhost:5432/finpilot
    username: yash
    password: Yash@0511
    driver-class-name: org.postgresql.Driver

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
    properties:
      hibernate:
        format_sql: true

  security:
    oauth2:
      client:
        registration:
          google:
            client-id: dummy
            client-secret: dummy

jwt:
  secret: 3b2d5f1a9c7e4b8d6f0a2c5e8d1f7a9b3c6d8e0f2a4b6c8d
  expiration: 86400000

marketdata:
  api:
    key: 3DEZJ48PU2TK3OUP
  base:
    url: https://www.alphavantage.co

app:
  frontend:
    allowed-origins: http://localhost:5173